library:
  source-dirs:
  - src
  exposed-modules:
  - CF
  - CF.CFConfig
  - MagicCP
  - MagicCP.SearchOptions

ghc-options:
  - -Wall

executable:
  main: Main.hs
  source-dirs: exe
  dependencies:
    - MagicCP

dependencies:
- MagicHaskeller
- aeson
- array
- base
- bytestring
- configurator
- clock
- curl-aeson
- directory
- filepath
- http-conduit
- html-conduit
- process
- syb
- template-haskell
- time
- text
- text
- xml-conduit
- split
- containers
name: MagicCP
