resolver: lts-14.0
# resolver: lts-9.21
# first found lts-3.22

# User packages to be built.
packages:
- MagicHaskeller
- .

# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#

extra-deps:
  # - cgi-3001.4.0.0
  # - mueval-0.9.3
  # - exceptions-0.10.2
  # - show-0.6
- containers-0.6.0.1
- curl-aeson-0.0.4
- exceptions-0.10.2
- http-conduit-2.3.7.1
- mueval-0.9.3
- show-0.6
- deepseq-1.4.4.0
- data-default-class-0.1.2.0
- clock-0.8
- split-0.2.3.4@sha256:048c75891d63a03828f97667214aaaf0e67b7dcbfec297753e39939ffda6f51a,2647


# Override default flag values for local packages and extra-deps
flags: {}
